image:
  repository: busybox
  tag: 0.3.0   # example for http-echo
  command: #ongoing command for the container stay alive
    - sleep
    - "3600"

replicaCount: 1

service:
  type: ClusterIP
  port: 80