apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: dev
spec:
  containers:
    - name: app
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80