apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: dev
spec:
  containers:
    - name: app
      image: busybox
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80